name: Flutter Build, Windows Inno Setup & Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Inno Setup Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Run inno_bundle to create installer
        run: dart run inno_bundle

      - name: Upload Windows installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/windows/runner/Release/*.exe

  build-android:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android release APK
        run: flutter build apk --release

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
